# Generated by Django 5.1 on 2024-09-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'news_domain_table_new',
            },
        ),
    ]
