# Generated by Django 5.1 on 2024-09-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_news', '0002_newsdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawnews',
            name='domain_name',
        ),
        migrations.AlterModelTable(
            name='rawnews',
            table='news_table_new',
        ),
    ]
