# Generated by Django 5.1 on 2024-09-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_news', '0003_remove_rawnews_domain_name_alter_rawnews_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnews',
            name='domain_id',
            field=models.IntegerField(null=True),
        ),
    ]
