# Generated by Django 5.1 on 2024-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_news', '0004_rawnews_domain_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedNews',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'processed_news_table_new',
            },
        ),
    ]
