# Generated by Django 5.1 on 2024-09-21 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_news', '0005_processednews'),
    ]

    operations = [
        migrations.AddField(
            model_name='processednews',
            name='processed_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='newsdomain',
            table='news_domain_table',
        ),
        migrations.AlterModelTable(
            name='processednews',
            table='processed_news_table',
        ),
        migrations.AlterModelTable(
            name='rawnews',
            table='news_table',
        ),
    ]
