# Generated by Django 5.1 on 2024-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_news', '0006_processednews_processed_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawnews',
            name='processed',
            field=models.IntegerField(default=0),
        ),
    ]
