# Generated by Django 5.1 on 2024-09-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_news', '0007_alter_rawnews_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='raw_news.rawnews')),
            ],
            options={
                'db_table': 'news_images_table',
            },
        ),
    ]
